config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  draw(:api)
  draw(:spi)

  # #### #
  # Auth #
  # #### #
  devise_for :users, controllers: {
    sessions: "auth/sessions",
    registrations: "auth/registrations",
    omniauth_callbacks: "auth/omniauth_callbacks",
    confirmations: "auth/confirmations",
    passwords: "auth/passwords"
  }

  devise_scope :user do
    get "confirmations/required" => "auth/confirmations#required", as: "auth_confirmation_required"
  end

  get "discourse/sso" => "discourse/sso"

  # ######## #
  # Webhooks #
  # ######## #
  namespace :webhooks do
    resource :stripe, only: [:create], controller: "stripe"
    resource :paypal, only: [:create], controller: "paypal" do
      post :ipn
    end
    resource :coinbase, only: [:create], controller: "coinbase"
    resource :github_sponsors, only: [:create]

    resource :issue_updates, only: [:create]
    resource :membership_updates, only: [:create]
    resource :push_updates, only: [:create]
    resource :pull_request_updates, only: [:create]
    resource :organization_updates, only: [:create]
    resource :workflow_run_updates, only: [:create]
  end

  # ##### #
  # Admin #
  # ##### #
  namespace :admin do
    root to: "dashboard#show"
    resources :insiders, controller: 'insiders'
    resources :community_videos
    resources :partners do
      resources :adverts
      resources :perks
    end
    resources :mailshots do
      member do
        patch :send_test
        patch :send_to_audience
      end
    end
    resources :streaming_events
    resources :donors, only: %i[index new create]
    resources :users, only: %i[index] do
      collection do
        get :search
      end
    end
  end

  # ############ #
  # Normal pages #
  # ############ #
  resource :settings, only: %i[show] do
    get :api_cli
    get :user_preferences
    get :communication_preferences
    get :donations
    get :integrations
    patch :reset_account
    delete :destroy_account
    delete :disconnect_discord
  end

  resource :dashboard, only: [:show], controller: "dashboard"

  resources :docs, only: %i[index]
  get 'docs/tracks/:track_slug', to: 'docs#track_index', as: :track_docs
  get 'docs/tracks/:track_slug/*slug', to: 'docs#track_show', as: :track_doc
  get 'docs/tracks', to: 'docs#tracks'
  get 'docs/:section/*slug', to: 'docs#show', as: :doc
  get 'docs/:section', to: 'docs#section', as: :docs_section

  resources :notifications, only: [:index]

  resources :impact, only: [:index]

  resources :solution_tagger, only: [:index]

  resource :images, controller: "images" do
    get "solutions/:track_slug/:exercise_slug/:user_handle", to: "images#solution"
    get "profiles/:user_handle", to: "images#profile"
  end

  resource :insiders, only: [:show], controller: "insiders" do
    get :payment_pending
  end

  resources :profiles, only: %i[index show new create] do
    collection do
      get :intro
    end

    member do
      get :tooltip

      get :solutions
      get :badges
      get :testimonials
      get :contributions
    end
  end

  namespace :mentoring do
    get "/", to: "external#show"
    resource :inbox, only: [:show], controller: "inbox"
    resource :queue, only: [:show], controller: "queue"
    resources :external_requests, only: [:show], param: :uuid do
      patch :accept, on: :member
    end

    resources :requests, only: [:show], param: :uuid do
      get :unavailable, on: :member
    end
    resources :discussions, only: [:show]
    resources :testimonials, only: [:index]
    resources :automation, only: %i[index edit], param: :uuid do
      collection do
        get :with_feedback
        get :admin
        get :tooltip_locked
      end
    end
  end

  namespace :maintaining do
    root to: "dashboard#show"
    resources :submissions, only: [:index]
    resources :exercise_representations
    resources :site_updates, except: [:destroy]
  end

  namespace :contributing do
    root to: "dashboard#show"
    resources :contributors, only: [:index]
    resources :tasks, only: [:index], param: :uuid do
      get :tooltip, on: :member
    end
  end
  namespace :training_data do
    root to: "dashboard#index"

    get "external" => "external#index"
    patch "become_trainer" => "external#become_trainer"

    resources :code_tags_samples, only: %i[index show] do
      get :next, on: :collection
    end
  end

  resource :community, only: %i[show], controller: "community"

  namespace :community do
    resources :stories, only: %i[index show]
    resources :videos, only: %i[index show]
    resources :brief_introductions, only: %i[index]
    resources :interviews, only: %i[index]
  end

  resources :tracks, only: %i[index show] do
    get :about, on: :member

    resource :build, only: %i[show], controller: "tracks/build" do
      get :syllabus_tooltip
      get :representer_tooltip
      get :analyzer_tooltip
      get :test_runner_tooltip
      get :practice_exercises_tooltip
    end

    resources :concepts, only: %i[index show], controller: "tracks/concepts" do
      get :tooltip, on: :member
    end

    resources :exercises, only: %i[index show edit], controller: "tracks/exercises" do
      member do
        get :tooltip
        get :no_test_runner
      end

      resources :iterations, only: [:index], controller: "tracks/iterations"

      resource :mentor_request, only: %i[new show], controller: "tracks/mentor_requests" do
        get :no_slots_remaining
        get :get_more_slots
      end
      resources :mentor_discussions, only: %i[index show], controller: "tracks/mentor_discussions" do
        collection do
          get :tooltip_locked
        end
      end
      resources :solutions, only: %i[index show], controller: "tracks/community_solutions" do
        collection do
          get :tooltip_locked
        end
      end

      resources :articles, only: %i[index show], controller: "tracks/articles"
      resources :approaches, only: %i[index show], controller: "tracks/approaches"

      resource :dig_deeper, only: %i[show], controller: "tracks/dig_deeper" do
        get :tooltip_locked
      end
    end

    member do
      post :join
    end
  end
  resources :exercises, only: %i[show], controller: "generic_exercises", as: :generic_exercises do
    member do
      get :approaches
    end
  end

  resource :user_onboarding, only: %i[show create], controller: "user_onboarding"
  resource :journey, only: [:show], controller: "journey" do
    member do
      get :solutions
      get :reputation
      get :badges
    end
  end

  resources :challenges, only: [:show] do
    post :start, on: :member
    get :implementation_status, on: :member
    get "implementation_status/:track_slug" => "challenges#track_implementation_status", on: :member, as: :track_implementation_status
  end

  # ############ #
  # Unsubscribe  #
  # ############ #
  resource :unsubscribe, only: %i[show update], controller: "unsubscribe" do
    patch :all
  end

  # #### #
  # Blog #
  # #### #
  resources :blog_posts, only: %i[index show], path: "blog"

  get "donate" => "donations#index", as: :donate
  get "donated" => "donations#donated", as: :donated

  # #### #
  # SEO #
  # #### #
  get "robots" => "sitemaps#robots_txt", as: :robots_txt
  get "sitemap" => "sitemaps#index", as: :sitemap
  get "sitemap-general" => "sitemaps#general", as: :sitemap_general
  get "sitemap-profiles" => "sitemaps#profiles", as: :sitemap_profiles
  get "sitemap-tracks-:track_id" => "sitemaps#track", as: :sitemap_track

  root to: "pages#index"

  ##############
  # ELB routes #
  ##############
  get "health-check", to: 'pages#health_check'

  ##########
  # Errors #
  ##########
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
  get "/503", to: "errors#internal_error"

  ###################
  # Adverts & Perks #
  ###################
  resources :adverts, controller: "partner/adverts", only: [] do
    get :redirect, on: :member
  end
  resources :perks, only: %i[index show] do
    get :claim, on: :member
  end

  ###############
  # About Pages #
  ###############
  resource :about, controller: 'about', only: [:show] do
    resources :partners, only: %i[index show], path: "supporters/organisations", controller: "about/partners"

    get :impact
    get :testimonials
    get :team
    get :hiring
    get :hiring_content, path: "hiring/content-2", as: :hiring_2
    get :hiring_community, path: "hiring/community-3", as: :hiring_3
    get :hiring_front_end_developer, path: "hiring/front-end-developer-4", as: :hiring_4
    get :hiring_rails_developer, path: "hiring/rails-developer-5", as: :hiring_5
    get :individual_supporters, path: "supporters/individuals", as: :individual_supporters
    # get :organisation_supporters, path: "supporters/organisations", as: :organisation_supporters

    # %w[packt gobridge].each do |supporter|
    #   get "supporter_#{supporter}".to_sym, path: "supporters/organisations/#{supporter}", as: "supporter_#{supporter}"
    # end
  end

  #########
  # Cohorts #
  #########
  resources :cohorts, only: [:show] do
    post :join, on: :member
  end

  #########
  # Pages #
  #########
  get "cli-walkthrough" => "pages#cli_walkthrough", as: :cli_walkthrough

  ############
  # Partners #
  ############
  get "partners/gobridge" => "partners#gobridge", as: :gobridge_partner_page
  get "partners/code-capsules/advert_redirect" => "partners#code_capsules_advert_redirect"
  get "partners/go-developer-network", to: redirect("partners/gobridge")
  get "partners/gdn", to: redirect("partners/gobridge")

  ##################
  # Special routes #
  ##################
  get "site.webmanifest" => "meta#site_webmanifest"

app/models/mailshot.rb
class Mailshot < ApplicationRecord
  has_markdown_field :content, strip_h1: false

  def sent_to_audiences = super.to_a.to_set

  def email_communication_preferences_key
    super&.to_sym
  end

  # This should return:
  # - an ActiveRecord relation that is paginatable
  # - a lambda that takes a record (from the relation) and returns the
  #   relevant user from it, or nil if there's no appropiate user (e.g. if a filter condition fails).
  def audience_for(type, slug)
    send("audience_for_#{type}", slug)
  end

  # This is pretty terribly slow and should only be used rarely.
  def audience_for_admins(_)
    [
      User.with_data.where("JSON_CONTAINS(user_data.roles, ?, '$')", %("admin")),
      ->(user) { user }
    ]
  end

  def audience_for_donors(_) = [User::Data.donors, ->(user_data) { user_data.user }]
  def audience_for_insiders(_) = [User.insiders, ->(user) { user }]

  def audience_for_reputation(min_rep)
    [
      User.where('reputation >= ?', min_rep),
      ->(user) { user }
    ]
  end

  def audience_for_recent(days)
    [
      User.with_data.where('user_data.last_visited_on >= ?', Time.current - days.to_i.days),
      lambda do |user|
        return unless user.iterations.count >= 2

        user
      end
    ]
  end

  def audience_for_track(slug)
    [
      UserTrack.where(track: Track.find_by!(slug:)).includes(:user),
      lambda do |user_track|
        return unless user_track.num_completed_exercises >= 2

        user_track.user
      end
    ]
  end

  def audience_for_challenge(slug)
    [
      User::Challenge.where(challenge_id: slug).includes(:user),
      ->(uc) { uc.user }
    ]
  end
end

app/models/user/mailshot.rb
class User::Mailshot < ApplicationRecord
  belongs_to :mailshot, class_name: "::Mailshot"

  delegate :email_communication_preferences_key, to: :mailshot

  include Emailable

  belongs_to :user
end

app/controllers/admin/mailshots_controller.rb
class Admin::MailshotsController < Admin::BaseController
  before_action :ensure_iHiD!
  before_action :set_mailshot, only: %i[show edit update destroy send_test send_to_audience]

  # GET /admin/mailshots
  def index
    @mailshots = Mailshot.all
    @send_counts = User::Mailshot.group(:mailshot_id).count
  end

  # GET /admin/mailshots/1
  def show
    @send_count = User::Mailshot.where(mailshot: @mailshot).count
    @audiences = %w[admins donors insiders challenge#12in23 challenge#48in24]
    @audiences += [100, 10, 3, 2, 1].map { |min| "reputation##{min}" }
    @audiences += [10, 30, 60, 90].map { |min| "recent##{min}" }
    @audiences += Track.pluck(:slug).map { |slug| "track##{slug}" }
  end

  # GET /admin/mailshots/new
  def new
    @mailshot = Mailshot.new
    setup_form
  end

  # GET /admin/mailshots/1/edit
  def edit
    setup_form
  end

  # POST /admin/mailshots
  def create
    @mailshot = Mailshot.new(mailshot_params)

    if @mailshot.save
      redirect_to [:admin, @mailshot], notice: "mailshot was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /admin/mailshots/1
  def update
    if @mailshot.update(mailshot_params)
      redirect_to [:admin, @mailshot], notice: "mailshot was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/mailshots/1
  def destroy
    @mailshot.destroy
    redirect_to admin_mailshots_url, notice: "mailshot was successfully destroyed."
  end

  def send_test
    Mailshot::SendTestMail.(@mailshot)

    flash[:mailshot_status] = "Test email sent!"

    redirect_to [:admin, @mailshot]
  end

  def send_to_audience
    audience_type, audience_slug = params[:audience].split("#")
    Mailshot::Send.(@mailshot, audience_type, audience_slug)

    flash[:mailshot_status] = "Email sent to audience: #{params[:audience]}!"

    redirect_to [:admin, @mailshot]
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_mailshot
    @mailshot = Mailshot.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def mailshot_params
    params.require(:mailshot).permit(
      :slug,
      :subject,
      :email_communication_preferences_key,
      :content_markdown,
      :text_content,
      :button_url,
      :button_text
    )
  end

  def setup_form
    @communication_preferences_keys = %i[
      receive_product_updates
      email_about_events
      email_about_insiders
      email_about_fundraising_campaigns
    ]
  end
end

app/views/admin/mailshots/_form.html.haml
= form_with(model: [:admin, mailshot]) do |form|
  - if mailshot.errors.any?
    .mb-12.text-red
      %h2
        = pluralize(mailshot.errors.count, "error")
        prohibited this mailshot from being saved:
      %ul
        - mailshot.errors.each do |error|
          %li= error.full_message

  .flex.flex-col
    .mb-12
      = form.label :slug, class: "block mb-4"
      = form.text_field :slug, class: 'w-fill'
    .mb-12
      = form.label :subject, class: "block mb-4"
      = form.text_field :subject, class: 'w-fill'
    .mb-12
      = form.label :email_communication_preferences_key, class: "block mb-4"
      .c-select= form.select :email_communication_preferences_key, communication_preferences_keys, class: 'w-fill'
    .mb-12
      = form.label :button_text, class: "block mb-4"
      = form.text_field :button_text, class: 'w-fill'
    .mb-12
      = form.label :button_url, class: "block mb-4"
      = form.text_field :button_url, class: 'w-fill'
    .mb-12
      = form.label :content_markdown, class: "block mb-4"
      = form.text_area :content_markdown, class: 'w-fill h-[400px]'
    .mb-12
      = form.label :text_content, class: "block mb-4"
      = form.text_area :text_content, class: 'w-fill h-[400px]'

    .mb-12
      = form.submit class: "btn btn-primary"

app/views/admin/mailshots/edit.html.haml
.lg-container
  %h1.text-h1 Editing mailshot
  = render "form", mailshot: @mailshot, communication_preferences_keys: @communication_preferences_keys
  %br/
  %div
    = link_to "Manage this mailshot", @amailshot
    |
    = link_to "Back to mailshots", admin_mailshots_path

app/views/admin/mailshots/index.html.haml
:css
  #admin-mailshots {
    padding:25px 0%;
    font-size: 16px;
    line-height:1.5;
  }
  h2 {
    font-size: 20px;
    margin-bottom: 16px;
  }
  table {
    width: 100%;
    border-collapse: collapse;
  }
  th {
    border: 1px solid #ddd;
    border-bottom: 1px solid #888;
    padding: 10px;
    text-align:left;
    font-weight:600px;
  }
  td {
    border: 1px solid #ddd;
    border-bottom: 1px solid #aaa;
    padding: 10px;
    vertical-align:top;
    max-width:300px;
  }

#admin-mailshots
  .lg-container
    %h1.text-h1.mb-8 Mailshots
    %table.mb-20
      %thead
        %tr
          %td Slug
          %td Subject
          %td.text-right Send count
          %td{ colspan: 2 }

      %tbody
      - @mailshots.each do |mailshot|
        %tr
          %td= mailshot.slug
          %td= mailshot.subject
          %td.text-right= @send_counts[mailshot.id]
          %td= link_to "Details", [:admin, mailshot]
          %td= link_to "Edit", edit_admin_mailshot_path(mailshot)
    .flex
      = link_to "New mailshot", new_admin_mailshot_path, class: 'btn btn-primary btn-base'

app/views/admin/mailshots/new.html.haml
.lg-container
  %h1.text-h1 New mailshot
  = render "form", mailshot: @mailshot, communication_preferences_keys: @communication_preferences_keys
  %br/
  %div
  = link_to "Back to mailshots", admin_mailshots_path

app/views/admin/mailshots/show.html.haml
.lg-container
  %h1.text-h1= @mailshot.slug

  .text-h6.mb-8 Slug: #{@mailshot.slug}
  .text-h6.mb-8 Subject: #{@mailshot.subject}
  .text-h6.mb-8 Preference Key: #{@mailshot.email_communication_preferences_key}
  .text-h6.mb-8 Num Sends: #{@send_count}
  .text-h6.mb-8 Created at: #{format_date(@mailshot.created_at)}
  .text-h6.mb-8 Test Sent?: #{@mailshot.test_sent ? 'Yes' : 'No'}

  - if @mailshot.sent_to_audiences.present?
    %h3.text-h3.mb-12 Sent to audiences
    %ul.text-h6.mb-20
      - @mailshot.sent_to_audiences.each do |audience|
        %li= audience

  %hr.my-24

  %h2.text-h3.mb-12 Sending Options
  .flex.flex-col
    - if flash[:mailshot_status]
      .mb-12.text-p-base.font-bold.text-darkSuccessGreen= flash[:mailshot_status]
    = button_to "Send test", send_test_admin_mailshot_path(@mailshot), method: :patch, class: 'btn btn-standard btn-base'

    - if @mailshot.test_sent?
      = form_tag send_to_audience_admin_mailshot_path, method: :patch, class: "flex flex-row items-center mt-20", data: { turbo_confirm: "Are you sure you want to send it to this audience?" } do
        .c-select
          = select_tag :audience, options_for_select(@audiences.map { |a| (a1 = a.split("#")) && [[a1[0].titleize, a1[1]].compact.join(": "), a] })
        = button_tag "Send to audience", class: 'btn btn-standard btn-base ml-8'

  %hr.my-24

  .flex
    = link_to "Edit this mailshot", edit_admin_mailshot_path(@mailshot), class: 'btn btn-standard btn-base'
    = link_to "Preview HTML", "/rails/mailers/mailshots/mailshot.html?slug=#{@mailshot.slug}", rel: "noopener", target: "_blank", class: 'btn btn-standard btn-base'
    = link_to "Preview Text", "/rails/mailers/mailshots/mailshot.txt?slug=#{@mailshot.slug}", rel: "noopener", target: "_blank", class: 'btn btn-standard btn-base'
    - if @send_count.zero?
      |
      = button_to "Destroy this mailshot", [:admin, @mailshot], method: :delete, data: { confirm: "Are you sure? Destroy #{@mailshot.slug}?" }, class: 'btn btn-warning'
    |
    = link_to "Back to all mailshots", admin_mailshots_path, class: 'btn btn-standard btn-base'