config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  draw(:api)
  draw(:spi)

  # #### #
  # Auth #
  # #### #
  devise_for :users, controllers: {
    sessions: "auth/sessions",
    registrations: "auth/registrations",
    omniauth_callbacks: "auth/omniauth_callbacks",
    confirmations: "auth/confirmations",
    passwords: "auth/passwords"
  }

  devise_scope :user do
    get "confirmations/required" => "auth/confirmations#required", as: "auth_confirmation_required"
  end

  get "discourse/sso" => "discourse/sso"

  # ######## #
  # Webhooks #
  # ######## #
  namespace :webhooks do
    resource :stripe, only: [:create], controller: "stripe"
    resource :paypal, only: [:create], controller: "paypal" do
      post :ipn
    end
    resource :coinbase, only: [:create], controller: "coinbase"
    resource :github_sponsors, only: [:create]

    resource :issue_updates, only: [:create]
    resource :membership_updates, only: [:create]
    resource :push_updates, only: [:create]
    resource :pull_request_updates, only: [:create]
    resource :organization_updates, only: [:create]
    resource :workflow_run_updates, only: [:create]
  end

  # ##### #
  # Admin #
  # ##### #
  namespace :admin do
    root to: "dashboard#show"
    resources :insiders, controller: 'insiders'
    resources :community_videos
    resources :partners do
      resources :adverts
      resources :perks
    end
    resources :mailshots do
      member do
        patch :send_test
        patch :send_to_audience
      end
    end
    resources :streaming_events
    resources :donors, only: %i[index new create]
    resources :users, only: %i[index] do
      collection do
        get :search
      end
    end
  end

  # ############ #
  # Normal pages #
  # ############ #
  resource :settings, only: %i[show] do
    get :api_cli
    get :user_preferences
    get :communication_preferences
    get :donations
    get :integrations
    patch :reset_account
    delete :destroy_account
    delete :disconnect_discord
  end

  resource :dashboard, only: [:show], controller: "dashboard"

  resources :docs, only: %i[index]
  get 'docs/tracks/:track_slug', to: 'docs#track_index', as: :track_docs
  get 'docs/tracks/:track_slug/*slug', to: 'docs#track_show', as: :track_doc
  get 'docs/tracks', to: 'docs#tracks'
  get 'docs/:section/*slug', to: 'docs#show', as: :doc
  get 'docs/:section', to: 'docs#section', as: :docs_section

  resources :notifications, only: [:index]

  resources :impact, only: [:index]

  resources :solution_tagger, only: [:index]

  resource :images, controller: "images" do
    get "solutions/:track_slug/:exercise_slug/:user_handle", to: "images#solution"
    get "profiles/:user_handle", to: "images#profile"
  end

  resource :insiders, only: [:show], controller: "insiders" do
    get :payment_pending
  end

  resources :profiles, only: %i[index show new create] do
    collection do
      get :intro
    end

    member do
      get :tooltip

      get :solutions
      get :badges
      get :testimonials
      get :contributions
    end
  end

  namespace :mentoring do
    get "/", to: "external#show"
    resource :inbox, only: [:show], controller: "inbox"
    resource :queue, only: [:show], controller: "queue"
    resources :external_requests, only: [:show], param: :uuid do
      patch :accept, on: :member
    end

    resources :requests, only: [:show], param: :uuid do
      get :unavailable, on: :member
    end
    resources :discussions, only: [:show]
    resources :testimonials, only: [:index]
    resources :automation, only: %i[index edit], param: :uuid do
      collection do
        get :with_feedback
        get :admin
        get :tooltip_locked
      end
    end
  end

  namespace :maintaining do
    root to: "dashboard#show"
    resources :submissions, only: [:index]
    resources :exercise_representations
    resources :site_updates, except: [:destroy]
  end

  namespace :contributing do
    root to: "dashboard#show"
    resources :contributors, only: [:index]
    resources :tasks, only: [:index], param: :uuid do
      get :tooltip, on: :member
    end
  end
  namespace :training_data do
    root to: "dashboard#index"

    get "external" => "external#index"
    patch "become_trainer" => "external#become_trainer"

    resources :code_tags_samples, only: %i[index show] do
      get :next, on: :collection
    end
  end

  resource :community, only: %i[show], controller: "community"

  namespace :community do
    resources :stories, only: %i[index show]
    resources :videos, only: %i[index show]
    resources :brief_introductions, only: %i[index]
    resources :interviews, only: %i[index]
  end

  resources :tracks, only: %i[index show] do
    get :about, on: :member

    resource :build, only: %i[show], controller: "tracks/build" do
      get :syllabus_tooltip
      get :representer_tooltip
      get :analyzer_tooltip
      get :test_runner_tooltip
      get :practice_exercises_tooltip
    end

    resources :concepts, only: %i[index show], controller: "tracks/concepts" do
      get :tooltip, on: :member
    end

    resources :exercises, only: %i[index show edit], controller: "tracks/exercises" do
      member do
        get :tooltip
        get :no_test_runner
      end

      resources :iterations, only: [:index], controller: "tracks/iterations"

      resource :mentor_request, only: %i[new show], controller: "tracks/mentor_requests" do
        get :no_slots_remaining
        get :get_more_slots
      end
      resources :mentor_discussions, only: %i[index show], controller: "tracks/mentor_discussions" do
        collection do
          get :tooltip_locked
        end
      end
      resources :solutions, only: %i[index show], controller: "tracks/community_solutions" do
        collection do
          get :tooltip_locked
        end
      end

      resources :articles, only: %i[index show], controller: "tracks/articles"
      resources :approaches, only: %i[index show], controller: "tracks/approaches"

      resource :dig_deeper, only: %i[show], controller: "tracks/dig_deeper" do
        get :tooltip_locked
      end
    end

    member do
      post :join
    end
  end
  resources :exercises, only: %i[show], controller: "generic_exercises", as: :generic_exercises do
    member do
      get :approaches
    end
  end

  resource :user_onboarding, only: %i[show create], controller: "user_onboarding"
  resource :journey, only: [:show], controller: "journey" do
    member do
      get :solutions
      get :reputation
      get :badges
    end
  end

  resources :challenges, only: [:show] do
    post :start, on: :member
    get :implementation_status, on: :member
    get "implementation_status/:track_slug" => "challenges#track_implementation_status", on: :member, as: :track_implementation_status
  end

  # ############ #
  # Unsubscribe  #
  # ############ #
  resource :unsubscribe, only: %i[show update], controller: "unsubscribe" do
    patch :all
  end

  # #### #
  # Blog #
  # #### #
  resources :blog_posts, only: %i[index show], path: "blog"

  get "donate" => "donations#index", as: :donate
  get "donated" => "donations#donated", as: :donated

  # #### #
  # SEO #
  # #### #
  get "robots" => "sitemaps#robots_txt", as: :robots_txt
  get "sitemap" => "sitemaps#index", as: :sitemap
  get "sitemap-general" => "sitemaps#general", as: :sitemap_general
  get "sitemap-profiles" => "sitemaps#profiles", as: :sitemap_profiles
  get "sitemap-tracks-:track_id" => "sitemaps#track", as: :sitemap_track

  root to: "pages#index"

  ##############
  # ELB routes #
  ##############
  get "health-check", to: 'pages#health_check'

  ##########
  # Errors #
  ##########
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
  get "/503", to: "errors#internal_error"

  ###################
  # Adverts & Perks #
  ###################
  resources :adverts, controller: "partner/adverts", only: [] do
    get :redirect, on: :member
  end
  resources :perks, only: %i[index show] do
    get :claim, on: :member
  end

  ###############
  # About Pages #
  ###############
  resource :about, controller: 'about', only: [:show] do
    resources :partners, only: %i[index show], path: "supporters/organisations", controller: "about/partners"

    get :impact
    get :testimonials
    get :team
    get :hiring
    get :hiring_content, path: "hiring/content-2", as: :hiring_2
    get :hiring_community, path: "hiring/community-3", as: :hiring_3
    get :hiring_front_end_developer, path: "hiring/front-end-developer-4", as: :hiring_4
    get :hiring_rails_developer, path: "hiring/rails-developer-5", as: :hiring_5
    get :individual_supporters, path: "supporters/individuals", as: :individual_supporters
    # get :organisation_supporters, path: "supporters/organisations", as: :organisation_supporters

    # %w[packt gobridge].each do |supporter|
    #   get "supporter_#{supporter}".to_sym, path: "supporters/organisations/#{supporter}", as: "supporter_#{supporter}"
    # end
  end

  #########
  # Cohorts #
  #########
  resources :cohorts, only: [:show] do
    post :join, on: :member
  end

  #########
  # Pages #
  #########
  get "cli-walkthrough" => "pages#cli_walkthrough", as: :cli_walkthrough

  ############
  # Partners #
  ############
  get "partners/gobridge" => "partners#gobridge", as: :gobridge_partner_page
  get "partners/code-capsules/advert_redirect" => "partners#code_capsules_advert_redirect"
  get "partners/go-developer-network", to: redirect("partners/gobridge")
  get "partners/gdn", to: redirect("partners/gobridge")

  ##################
  # Special routes #
  ##################
  get "site.webmanifest" => "meta#site_webmanifest"

app/models/streaming_event.rb
class StreamingEvent < ApplicationRecord
  scope :live, -> { where('starts_at <= ? AND ends_at >= ?', Time.current, Time.current) }
  scope :scheduled, -> { where('starts_at > ?', Time.current) }
  scope :featured, -> { where(featured: true) }

  def self.next_featured = scheduled.featured.order(:starts_at).first
  def self.next_5 = scheduled.order(:starts_at).first(5)

  def youtube? = youtube_id.present?

  def youtube_external_url
    "https://www.youtube.com/watch?v=#{youtube_id}" if youtube?
  end

  def youtube_embed_url
    "https://www.youtube.com/embed/#{youtube_id}" if youtube?
  end
end

app/controllers/admin/streaming_events_controller.rb
class Admin::StreamingEventsController < Admin::BaseController
  before_action :ensure_admin!
  before_action :set_streaming_event, only: %i[show edit update destroy]

  # GET /admin/streaming_events
  def index
    @streaming_events = StreamingEvent.all
  end

  # GET /admin/streaming_events/1
  def show; end

  # GET /admin/streaming_events/new
  def new
    @streaming_event = StreamingEvent.new
  end

  # GET /admin/streaming_events/1/edit
  def edit; end

  # POST /admin/streaming_events
  def create
    @streaming_event = StreamingEvent.new(streaming_event_params)

    if @streaming_event.save
      redirect_to [:admin, @streaming_event], notice: "Streaming event was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /admin/streaming_events/1
  def update
    if @streaming_event.update(streaming_event_params)
      redirect_to [:admin, @streaming_event], notice: "Streaming event was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/streaming_events/1
  def destroy
    @streaming_event.destroy
    redirect_to admin_streaming_events_url, notice: "Streaming event was successfully destroyed."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_streaming_event
    @streaming_event = StreamingEvent.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def streaming_event_params
    params.require(:streaming_event).permit(:title, :description, :starts_at, :ends_at, :featured, :youtube_id, :thumbnail_url)
  end
end

app/controllers/api/streaming_events_controller.rb
class API::StreamingEventsController < API::BaseController
  def index
    render json: AssembleStreamingEvents.(params.permit(*AssembleStreamingEvents.keys))
  end
end

app/views/admin/streaming_events/_form.html.haml
= form_with(model: [:admin, streaming_event]) do |form|
  - if streaming_event.errors.any?
    .mb-12.text-red
      %h2
        = pluralize(streaming_event.errors.count, "error")
        prohibited this streaming_event from being saved:
      %ul
        - streaming_event.errors.each do |error|
          %li= error.full_message
  .flex.flex-col
    .mb-12
      = form.label :title, class: "block mb-4"
      = form.text_field :title, class: 'w-fill'
    .mb-12
      = form.label :description, class: "block mb-4"
      = form.text_area :description, class: 'w-fill'
    .mb-12
      = form.label :starts_at, class: "block mb-4"
      = form.datetime_field :starts_at
    .mb-12
      = form.label :ends_at, class: "block mb-4"
      = form.datetime_field :ends_at
    .mb-12
      = form.label :featured, class: "block mb-4"
      = form.check_box :featured
    .mb-12
      = form.label :youtube_id, class: "block mb-4"
      = form.text_field :youtube_id
    .mb-12
      = form.label :thumbnail_url, class: "block mb-4"
      = form.text_field :thumbnail_url
    .mb-12
      = form.submit class: "btn btn-primary"

app/views/admin/streaming_events/edit.html.haml
.lg-container
  %h1.text-h1 Editing streaming event
  = render "form", streaming_event: @streaming_event
  %br/
  %div
    = link_to "Show this streaming event", @astreaming_event
    |
    = link_to "Back to streaming events", admin_streaming_events_path

app/views/admin/streaming_events/index.html.haml
.c-admin-page
  .lg-container
    %h1.text-h1.mb-8 Streaming events
    %table.c-admin-table.mb-8
      - @streaming_events.each do |streaming_event|
        %tr
          %td= streaming_event.title
          %td= format_datetime(streaming_event.starts_at)
          %td= link_to "Details", [:admin, streaming_event]
          %td= link_to "Edit", edit_admin_streaming_event_path(streaming_event)
    .flex
      = link_to "New streaming event", new_admin_streaming_event_path, class: 'btn btn-primary btn-base'

app/views/admin/streaming_events/new.html.haml
.lg-container
  %h1.text-h1 New streaming event
  = render "form", streaming_event: @streaming_event
  %br/
  %div
  = link_to "Back to streaming events", admin_streaming_events_path

app/views/admin/streaming_events/show.html.haml
.lg-container
  %h1.text-h1= @streaming_event.title

  .text-h6.mb-8 Title: #{@streaming_event.title}
  .text-h6.mb-8 Description: #{@streaming_event.description}
  .text-h6.mb-8 Starts at: #{format_date(@streaming_event.starts_at)}
  .text-h6.mb-8 Ends at: #{format_date(@streaming_event.ends_at)}
  .text-h6.mb-8 Featured #{@streaming_event.featured? ? 'Yes' : 'No'}
  .text-h6.mb-8 Thumbnail: #{@streaming_event.thumbnail_url}
  .text-h6.mb-8 YouTube ID: #{@streaming_event.youtube_id}

  .flex
    = link_to "Edit this streaming event", edit_admin_streaming_event_path(@streaming_event), class: 'btn btn-standard btn-base'
    |
    = button_to "Destroy this event", [:admin, @streaming_event], method: :delete, data: { confirm: "Are you sure? Destroy #{@streaming_event.title}?" }, class: 'btn btn-warning'
    |
    = link_to "Back to all streaming events", admin_streaming_events_path, class: 'btn btn-standard btn-base'