config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  draw(:api)
  draw(:spi)

  # #### #
  # Auth #
  # #### #
  devise_for :users, controllers: {
    sessions: "auth/sessions",
    registrations: "auth/registrations",
    omniauth_callbacks: "auth/omniauth_callbacks",
    confirmations: "auth/confirmations",
    passwords: "auth/passwords"
  }

  devise_scope :user do
    get "confirmations/required" => "auth/confirmations#required", as: "auth_confirmation_required"
  end

  get "discourse/sso" => "discourse/sso"

  # ######## #
  # Webhooks #
  # ######## #
  namespace :webhooks do
    resource :stripe, only: [:create], controller: "stripe"
    resource :paypal, only: [:create], controller: "paypal" do
      post :ipn
    end
    resource :coinbase, only: [:create], controller: "coinbase"
    resource :github_sponsors, only: [:create]

    resource :issue_updates, only: [:create]
    resource :membership_updates, only: [:create]
    resource :push_updates, only: [:create]
    resource :pull_request_updates, only: [:create]
    resource :organization_updates, only: [:create]
    resource :workflow_run_updates, only: [:create]
  end

  # ##### #
  # Admin #
  # ##### #
  namespace :admin do
    root to: "dashboard#show"
    resources :insiders, controller: 'insiders'
    resources :community_videos
    resources :partners do
      resources :adverts
      resources :perks
    end
    resources :mailshots do
      member do
        patch :send_test
        patch :send_to_audience
      end
    end
    resources :streaming_events
    resources :donors, only: %i[index new create]
    resources :users, only: %i[index] do
      collection do
        get :search
      end
    end
  end

  # ############ #
  # Normal pages #
  # ############ #
  resource :settings, only: %i[show] do
    get :api_cli
    get :user_preferences
    get :communication_preferences
    get :donations
    get :integrations
    patch :reset_account
    delete :destroy_account
    delete :disconnect_discord
  end

  resource :dashboard, only: [:show], controller: "dashboard"

  resources :docs, only: %i[index]
  get 'docs/tracks/:track_slug', to: 'docs#track_index', as: :track_docs
  get 'docs/tracks/:track_slug/*slug', to: 'docs#track_show', as: :track_doc
  get 'docs/tracks', to: 'docs#tracks'
  get 'docs/:section/*slug', to: 'docs#show', as: :doc
  get 'docs/:section', to: 'docs#section', as: :docs_section

  resources :notifications, only: [:index]

  resources :impact, only: [:index]

  resources :solution_tagger, only: [:index]

  resource :images, controller: "images" do
    get "solutions/:track_slug/:exercise_slug/:user_handle", to: "images#solution"
    get "profiles/:user_handle", to: "images#profile"
  end

  resource :insiders, only: [:show], controller: "insiders" do
    get :payment_pending
  end

  resources :profiles, only: %i[index show new create] do
    collection do
      get :intro
    end

    member do
      get :tooltip

      get :solutions
      get :badges
      get :testimonials
      get :contributions
    end
  end

  namespace :mentoring do
    get "/", to: "external#show"
    resource :inbox, only: [:show], controller: "inbox"
    resource :queue, only: [:show], controller: "queue"
    resources :external_requests, only: [:show], param: :uuid do
      patch :accept, on: :member
    end

    resources :requests, only: [:show], param: :uuid do
      get :unavailable, on: :member
    end
    resources :discussions, only: [:show]
    resources :testimonials, only: [:index]
    resources :automation, only: %i[index edit], param: :uuid do
      collection do
        get :with_feedback
        get :admin
        get :tooltip_locked
      end
    end
  end

  namespace :maintaining do
    root to: "dashboard#show"
    resources :submissions, only: [:index]
    resources :exercise_representations
    resources :site_updates, except: [:destroy]
  end

  namespace :contributing do
    root to: "dashboard#show"
    resources :contributors, only: [:index]
    resources :tasks, only: [:index], param: :uuid do
      get :tooltip, on: :member
    end
  end
  namespace :training_data do
    root to: "dashboard#index"

    get "external" => "external#index"
    patch "become_trainer" => "external#become_trainer"

    resources :code_tags_samples, only: %i[index show] do
      get :next, on: :collection
    end
  end

  resource :community, only: %i[show], controller: "community"

  namespace :community do
    resources :stories, only: %i[index show]
    resources :videos, only: %i[index show]
    resources :brief_introductions, only: %i[index]
    resources :interviews, only: %i[index]
  end

  resources :tracks, only: %i[index show] do
    get :about, on: :member

    resource :build, only: %i[show], controller: "tracks/build" do
      get :syllabus_tooltip
      get :representer_tooltip
      get :analyzer_tooltip
      get :test_runner_tooltip
      get :practice_exercises_tooltip
    end

    resources :concepts, only: %i[index show], controller: "tracks/concepts" do
      get :tooltip, on: :member
    end

    resources :exercises, only: %i[index show edit], controller: "tracks/exercises" do
      member do
        get :tooltip
        get :no_test_runner
      end

      resources :iterations, only: [:index], controller: "tracks/iterations"

      resource :mentor_request, only: %i[new show], controller: "tracks/mentor_requests" do
        get :no_slots_remaining
        get :get_more_slots
      end
      resources :mentor_discussions, only: %i[index show], controller: "tracks/mentor_discussions" do
        collection do
          get :tooltip_locked
        end
      end
      resources :solutions, only: %i[index show], controller: "tracks/community_solutions" do
        collection do
          get :tooltip_locked
        end
      end

      resources :articles, only: %i[index show], controller: "tracks/articles"
      resources :approaches, only: %i[index show], controller: "tracks/approaches"

      resource :dig_deeper, only: %i[show], controller: "tracks/dig_deeper" do
        get :tooltip_locked
      end
    end

    member do
      post :join
    end
  end
  resources :exercises, only: %i[show], controller: "generic_exercises", as: :generic_exercises do
    member do
      get :approaches
    end
  end

  resource :user_onboarding, only: %i[show create], controller: "user_onboarding"
  resource :journey, only: [:show], controller: "journey" do
    member do
      get :solutions
      get :reputation
      get :badges
    end
  end

  resources :challenges, only: [:show] do
    post :start, on: :member
    get :implementation_status, on: :member
    get "implementation_status/:track_slug" => "challenges#track_implementation_status", on: :member, as: :track_implementation_status
  end

  # ############ #
  # Unsubscribe  #
  # ############ #
  resource :unsubscribe, only: %i[show update], controller: "unsubscribe" do
    patch :all
  end

  # #### #
  # Blog #
  # #### #
  resources :blog_posts, only: %i[index show], path: "blog"

  get "donate" => "donations#index", as: :donate
  get "donated" => "donations#donated", as: :donated

  # #### #
  # SEO #
  # #### #
  get "robots" => "sitemaps#robots_txt", as: :robots_txt
  get "sitemap" => "sitemaps#index", as: :sitemap
  get "sitemap-general" => "sitemaps#general", as: :sitemap_general
  get "sitemap-profiles" => "sitemaps#profiles", as: :sitemap_profiles
  get "sitemap-tracks-:track_id" => "sitemaps#track", as: :sitemap_track

  root to: "pages#index"

  ##############
  # ELB routes #
  ##############
  get "health-check", to: 'pages#health_check'

  ##########
  # Errors #
  ##########
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
  get "/503", to: "errors#internal_error"

  ###################
  # Adverts & Perks #
  ###################
  resources :adverts, controller: "partner/adverts", only: [] do
    get :redirect, on: :member
  end
  resources :perks, only: %i[index show] do
    get :claim, on: :member
  end

  ###############
  # About Pages #
  ###############
  resource :about, controller: 'about', only: [:show] do
    resources :partners, only: %i[index show], path: "supporters/organisations", controller: "about/partners"

    get :impact
    get :testimonials
    get :team
    get :hiring
    get :hiring_content, path: "hiring/content-2", as: :hiring_2
    get :hiring_community, path: "hiring/community-3", as: :hiring_3
    get :hiring_front_end_developer, path: "hiring/front-end-developer-4", as: :hiring_4
    get :hiring_rails_developer, path: "hiring/rails-developer-5", as: :hiring_5
    get :individual_supporters, path: "supporters/individuals", as: :individual_supporters
    # get :organisation_supporters, path: "supporters/organisations", as: :organisation_supporters

    # %w[packt gobridge].each do |supporter|
    #   get "supporter_#{supporter}".to_sym, path: "supporters/organisations/#{supporter}", as: "supporter_#{supporter}"
    # end
  end

  #########
  # Cohorts #
  #########
  resources :cohorts, only: [:show] do
    post :join, on: :member
  end

  #########
  # Pages #
  #########
  get "cli-walkthrough" => "pages#cli_walkthrough", as: :cli_walkthrough

  ############
  # Partners #
  ############
  get "partners/gobridge" => "partners#gobridge", as: :gobridge_partner_page
  get "partners/code-capsules/advert_redirect" => "partners#code_capsules_advert_redirect"
  get "partners/go-developer-network", to: redirect("partners/gobridge")
  get "partners/gdn", to: redirect("partners/gobridge")

  ##################
  # Special routes #
  ##################
  get "site.webmanifest" => "meta#site_webmanifest"

app/models/partner.rb
class Partner < ApplicationRecord
  has_one_attached :light_logo
  has_one_attached :dark_logo

  has_markdown_field :support
  has_markdown_field :description

  has_many :adverts, dependent: :destroy
  has_many :perks, dependent: :destroy

  def website_domain
    PublicSuffix.domain(URI.parse(website_url).host)
  rescue StandardError
    ""
  end

  def to_param
    slug
  end
end

app/models/partner/advert.rb
class Partner::Advert < ApplicationRecord
  belongs_to :partner
  has_one_attached :light_logo
  has_one_attached :dark_logo

  enum status: { pending: 0, active: 1, out_of_budget: 2, retired: 3 }

  before_create do
    self.uuid = SecureRandom.compact_uuid
  end

  def to_param
    uuid
  end
end

app/models/partner/perk.rb
class Partner::Perk < ApplicationRecord
  belongs_to :partner
  has_one_attached :light_logo
  has_one_attached :dark_logo

  has_markdown_field :general_offer_summary
  has_markdown_field :insiders_offer_summary

  enum audience: { general: 0, insider: 1 }
  enum status: { pending: 0, active: 1, out_of_budget: 2, retired: 3 }

  before_create do
    self.uuid = SecureRandom.compact_uuid
  end

  def to_param
    uuid
  end

  def url_for_user(user)
    user&.insider? && insiders_button_text.present? ?
    insiders_url : general_url
  end

  def offer_summary_html_for_user(user)
    user&.insider? && insiders_offer_summary_markdown.present? ?
    insiders_offer_summary_html : general_offer_summary_html
  end

  def button_text_for_user(user)
    user&.insider? && insiders_button_text.present? ?
    insiders_button_text : general_button_text
  end

  def offer_details_for_user(user)
    user&.insider? && insiders_offer_details.present? ?
    insiders_offer_details : general_offer_details
  end

  def voucher_code?
    general_voucher_code.present?
  end

  def voucher_code_for_user(user)
    user&.insider? && insiders_voucher_code.present? ?
    insiders_voucher_code : general_voucher_code
  end
end

app/controllers/about/partners_controller.rb
class About::PartnersController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @num_individual_supporters = User::Data.donors.count
    @partners = Partner.where.not(support_markdown: '')
  end

  def show
    @org = Partner.select(:name, :slug, :description_markdown).find_by!(slug: params[:id])
  end
end

app/controllers/admin/partners_controller.rb
class Admin::PartnersController < Admin::BaseController
  before_action :set_partner, only: %i[show edit update destroy]

  # GET /admin/partners
  def index
    @partners = Partner.order(name: :asc)
  end

  # GET /admin/partners/1
  def show; end

  # GET /admin/partners/new
  def new
    @partner = Partner.new
  end

  # GET /admin/partners/1/edit
  def edit; end

  # POST /admin/partners
  def create
    @partner = Partner.new(partner_params)

    if @partner.save
      redirect_to [:admin, @partner], notice: "Community video was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /admin/partners/1
  def update
    if @partner.update(partner_params)
      redirect_to [:admin, @partner], notice: "Community video was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/partners/1
  def destroy
    @partner.destroy
    redirect_to partners_url, notice: "Community video was successfully destroyed."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_partner
    @partner = Partner.find_by(slug: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def partner_params
    params.require(:partner).permit(
      :name, :slug, :website_url, :headline, :description_markdown, :support_markdown,
      :light_logo, :dark_logo
    )
  end
end

app/controllers/partner/adverts_controller.rb
class Partner::AdvertsController < ApplicationController
  skip_before_action :authenticate_user!

  def redirect
    advert = Partner::Advert.find_by!(uuid: params[:id])

    unless request.is_crawler?
      Partner::LogAdvertClick.defer(
        advert, current_user, Time.current, params[:impression_uuid]
      )
    end

    redirect_to advert.url, allow_other_host: true
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  skip_before_action :authenticate_user!

  def gobridge
    @track = Track.find('go')
    @num_concepts = @track.concepts.count
    @num_exercises = @track.exercises.count
    @num_tasks = @track.tasks.count
  end

  def code_capsules_advert_redirect
    url = user_signed_in? ?
      "https://exercism.org/perks/6471b0d6b42441bfa88fdc49e16e3425" :
      "https://codecapsules.io"
    redirect_to url, allow_other_host: true
  end
end

app/helpers/view_components/partner/advert.rb
module ViewComponents
  class Partner::Advert < ViewComponent
    include Mandate

    initialize_with advert: nil, track: nil, preview: false

    def to_s
      # Don't show adverts at all for crawlers
      return nil if request.is_crawler?
      return nil unless preview || show_advert?
      return nil unless advert

      uuid = SecureRandom.hex

      render(
        template: "components/advert",
        locals: { advert:, uuid: }
      ).tap do
        ::Partner::LogAdvertImpression.defer(
          uuid,
          advert, current_user, request.remote_ip,
          Time.current, request.path
        )
      end
    end

    private
    memoize
    def advert
      @advert || ::Partner::Advert.active.first
    end

    def show_advert?
      return false unless track
      return true if track.slug == "go"
      return true if %w[javascript python java].include?(track.slug) && ALLOWED_DATES.include?(Date.current)

      false
    end

    ALLOWED_DATES = [
      Date.new(2023, 8, 16)..Date.new(2023, 8, 21),
      Date.new(2023, 9, 14)..Date.new(2023, 9, 17),
      Date.new(2023, 10, 13)..Date.new(2023, 10, 16),
      Date.new(2023, 11, 3)..Date.new(2023, 11, 5)
    ].map(&:to_a).flatten.freeze
  end
end

app/helpers/view_components/partner/perk.rb
module ViewComponents
  class Partner::Perk < ViewComponent
    include Mandate

    initialize_with :perk, preview: false

    def to_s
      render(
        template: "components/perk",
        locals: {
          perk:,
          offer_summary_html: perk.offer_summary_html_for_user(current_user),
          button_tag: preview ? :div : :a,
          button_text: perk.button_text_for_user(current_user)
        }
      )
    end
  end
end

app/views/about/partners/gobridge.html.haml
- require_stylesheet "about"

#page-organisation-supporter
  %header.pb-60
    .md-container.flex.flex-col.items-center.c-shapes.c-shapes-1.text-center
      = link_to about_partners_path, class: "c-prominent-link mt-48 mb-24" do
        = graphical_icon "arrow-left"
        See all our supporters

      %h1.text-h0.flex.flex-col.items-center.text-center
        Exercism is supported by
        %br
        = icon "gobridge", "GoBridge", category: :partners, css_class: "logo gobridge"

  .md-container
    %article.flex.flex-col.md:flex-row
      .lhs
        %h2.text-h2 How GoBridge supports Exercism
        %hr.c-divider.mt-20.mb-28
        %p.text-p-xlarge.mb-40 In 2021 GoBridge make a significant donation to support the development of Exercism Teams, specifically allowing us to lay the foundations of student-mentor interactions within the new Exercism editor.

        %h2.text-h2 About GoBridge
        %hr.c-divider.mt-20.mb-28
        %p.text-p-xlarge.mb-16 GoBridge's mission is to enable minorities in tech to use Go as a tool to learn and teach programming and, ultimately, to empower underrepresented groups in tech to help increase diversity in the Go community. That fits perfectly with our mission of providing opportunity through the development of programming, and so we're really excited to be able to launch this partnership. GoBridge and the GDN will be promoting Exercism across their networks, and we'll be hoping for a large influx of both Go mentors and students.

      .rhs.mt-24.md:mt-0.md:ml-40
        - @blog_posts.each do |blog_post|
          = render ViewComponents::BlogPost.new(blog_post)

app/views/about/partners/index.html.haml
- content_for :meta_title, "Supporting Exercism"
- content_for :meta_description, "Can your organisation help Exercism grow? Become rocket fuel for our mission!"
- content_for :canonical_url, about_partners_url
- require_stylesheet "about"

= render ViewComponents::AboutNav.new(:organisation_supporters)

#page-organisation-supporters
  %header.pb-56.c-header-with-bg
    .md-container.flex.flex-col.items-center.c-shapes.c-shapes-1.text-center
      = graphical_icon "rocket", category: "graphics", css_class: "rocket mb-8"
      %h1.text-h0.mb-16
        Become
        %strong rocket fuel
        for our mission
      %p.text-p-2xlarge.text-textColor6.font-medium.mb-32
        Partner with us or donate to support our mission to bringing free code learning and practice to the world.
      .logos.flex.items-center.justify-center.flex-wrap.mb-44
        = icon "mozilla", "Mozilla", category: :partners, css_class: "mozilla"
        = icon "packt", "Packt Publishing", category: :partners, css_class: "packt"
        = icon "gobridge", "GoBridge", category: :partners, css_class: "gobridge"
        = icon "chicago", "University of Chicago", category: :partners, css_class: "chicago"

  .md-container.mb-48
    .cta.top-cta.flex.flex-col.lg:flex-row.lg:items-center.border-gradient.py-24.px-24.lg:px-40
      = image_tag "team/jeremy-walker.jpg", alt: "Photo of Jeremy Walker", class: 'mb-12 md:mb-0 md:mr-24 rounded-100'
      .text
        %h2.text-h4.mb-4 Want to discuss how you can help Exercism?
        %p.text-p-large
          Get in touch with
          = succeed(',') do
            %strong Jeremy Walker
          Exercism's CEO.

      = link_to "mailto:jeremy@exercism.org", class: 'btn-primary btn-m mt-16 lg:mt-0 lg:ml-auto md:px-80' do
        = graphical_icon "email"
        %span jeremy@exercism.org

  .md-container
    .flex.mb-48.md:mb-56.items-start.flex-col.md:flex-row
      .lhs
        = graphical_icon "target", css_class: "mb-16"
        %h2.text-h2.mb-20 Support from our funders is crucial to achieving Exercism's goals
        %hr.c-divider.mb-28
        %p.text-p-large.mb-16 While much of Exercism is run by our volunteer community, the website and core infrastructure are managed by a full-time team.
        %p.text-p-large.mb-16 We also undertake specific larger projects, such as the development of our automated analyzers, which require a committed team working more intensely on something over a fixed period of time.
        %p.text-p-large In order to fund this core team and these products we rely on grant funding from companies or organisation that wish to contribute to our vision of helping providing free programming education for everyone.

      = graphical_icon "target", category: :graphics, css_class: "mt-32 md:mt-0 md:ml-64 lg:ml-128"

    .areas-of-collaboration.pt-32.pb-56.px-32.md:px-64.flex.flex-col.items-center.bg-evenLighterBlue.rounded-8.mb-48.md:mb-56
      = graphical_icon "partnership", css_class: "mb-16"
      %h2.text-h2.text-center Areas in which organisations have supported us so far
      %hr.c-divider.mt-20.mb-32

      .grid.grid-cols-1.sm:grid-cols-2.md:grid-cols-3.gap-y-48.gap-x-32
        -# .item Diversity &amp; Inclusivity Initiatives
        .item Fundraising
        .item Research Projects
        .item Track Development
        .item Developing Automation
        -# .item Developing Mentor-Learner relationships
        .item Community Building
        .item Servers and infrastructure

    .supporters.flex.flex-col.items-center.mb-56
      %h2.text-h2.text-center Our Supporters
      %hr.c-divider.mt-20.mb-32

      .grid.grid-cols-1.md:grid-cols-2.gap-24
        - @partners.each do |partner|
          .supporter
            = image_tag partner.light_logo, alt: partner.name, class: "logo logo-light #{partner.slug}"
            = image_tag partner.dark_logo, alt: partner.name, class: "logo logo-dark #{partner.slug}"
            %p= raw partner.support_html
            - perk = partner.perks.active.first
            - if perk
              = render ViewComponents::ProminentLink.new("Learn more", perk_path(perk))
        .supporter
          = icon "chicago", "University of Chicago", category: :partners, css_class: "logo chicago"
          %p
            The
            %strong University of Chicago
            in partnership with
            %strong The Sloan Foundation
            funded the creation of Exercism v3 as part of a wider research project into how people evolve programming skills and knowledge across multiple languages.

        .supporter
          = icon "mozilla", "Mozilla", category: :partners, css_class: "logo mozilla"
          %p
            %strong Mozilla
            supported us in the creation of our automated analyzers. They funded the product design, prototype, and analyzer infrastructure, saving thousands of hours of mentors time, and dramatically reducing wait-times for students.

    .individuals.flex.flex-col.items-center.text-center.mb-56.text-balance
      = icon "individual-supporters", "Individual Supporters"
      %h2.text-h2 Exercism is also supported by #{@num_individual_supporters} generous individuals
      %hr.c-divider.mt-20.mb-28
      = render ViewComponents::ProminentLink.new("See all of our individual supporters", individual_supporters_about_path)

    .cta.flex.flex-col.lg:flex-row.lg:items-center.border-gradient.py-24.px-24.lg:px-40
      = image_tag "team/jeremy-walker.jpg", alt: "Photo of Jeremy Walker", class: 'mb-12 md:mb-0 md:mr-24 rounded-100'
      .text
        %h2.text-h4.mb-4 Want to discuss how you can help Exercism?
        %p.text-p-large
          Get in touch with
          = succeed(',') do
            %strong Jeremy Walker
          Exercism's CEO.

      = link_to "mailto:jeremy@exercism.org", class: 'btn-primary btn-m mt-16 lg:mt-0 lg:ml-auto md:px-80' do
        = graphical_icon "email"
        %span jeremy@exercism.org

app/views/about/partners/packt.html.haml
- require_stylesheet "about"

= render ViewComponents::AboutNav.new(:organisation_supporters)

#page-organisation-supporter
  %header.pb-60
    .md-container.flex.flex-col.items-center.c-shapes.c-shapes-1.text-center
      = link_to about_partners_path, class: "c-prominent-link mt-48 mb-24" do
        = graphical_icon "arrow-left"
        See all our supporters

      %h1.text-h0.flex.flex-col.items-center.text-center
        Exercism is supported by
        %br
        = icon "packt", "Packt Publishing", category: :partners, css_class: "logo packt"

  .md-container
    %article
      .lhs
        %h2.text-h2 #{@org.name} supports Exercism
        %hr.c-divider.mt-20.mb-28
        %p.text-p-xlarge.mb-40 Packt Publishing are a core Exercism partner, helping us develop both the fundraising and content side of the platform. They have sponsored our new Fundraising role, and we are currently developing a deeper partnership which we will launch in early 2022.

        %h2.text-h2 About Packt Publishing
        %hr.c-divider.mt-20.mb-28
        %p.text-p-xlarge.mb-16 Packt is a tech publisher focused on the practical application of technology. Packt authors are mostly working developers who do the job of sorting out what actually works and how to get things done with the endless stream of new technology. Packt readers and users are busy working engineers building solutions and applications, who want to know whether how a technology works in practice, and whether it’s worth using.
        %p.text-p-xlarge.mb-16 Packt supports Exercism in its mission to ease the path to fluency across languages. We share the Exercism values of independence from any one platform or language, and the belief in the desire of engineers to support and help each other as a peer community. Packt books and publishing aim to provide a structured body of practical knowledge to complement fantastic platforms like Exercism. We both provide a way for experienced professionals to share knowledge and experience with the tech broader community.