config/routes.rb
      resources :perks
    end
    resources :mailshots do
      member do
        patch :send_test
        patch :send_to_audience
      end
    end
    resources :streaming_events
    resources :donors, only: %i[index new create]
    resources :users, only: %i[index] do
      collection do
        get :search
      end
    end
  end

  # ############ #
  # Normal pages #
  # ############ #
  resource :settings, only: %i[show] do
    get :api_cli
    get :user_preferences
    get :communication_preferences
    get :donations
    get :integrations
    patch :reset_account
    delete :destroy_account
    delete :disconnect_discord
  end

  resource :dashboard, only: [:show], controller: "dashboard"

  resources :docs, only: %i[index]
  get 'docs/tracks/:track_slug', to: 'docs#track_index', as: :track_docs
  get 'docs/tracks/:track_slug/*slug', to: 'docs#track_show', as: :track_doc
  get 'docs/tracks', to: 'docs#tracks'
  get 'docs/:section/*slug', to: 'docs#show', as: :doc
  get 'docs/:section', to: 'docs#section', as: :docs_section

  resources :notifications, only: [:index]

  resources :impact, only: [:index]

  resources :solution_tagger, only: [:index]

  resource :images, controller: "images" do
    get "solutions/:track_slug/:exercise_slug/:user_handle", to: "images#solution"
    get "profiles/:user_handle", to: "images#profile"
  end

  resource :insiders, only: [:show], controller: "insiders" do
    get :payment_pending
  end

  resources :profiles, only: %i[index show new create] do
    collection do
      get :intro
    end

    member do
      get :tooltip

      get :solutions
      get :badges
      get :testimonials
      get :contributions
    end
  end

  namespace :mentoring do
    get "/", to: "external#show"
    resource :inbox, only: [:show], controller: "inbox"
    resource :queue, only: [:show], controller: "queue"
    resources :external_requests, only: [:show], param: :uuid do
      patch :accept, on: :member
    end

    resources :requests, only: [:show], param: :uuid do
      get :unavailable, on: :member
    end
    resources :discussions, only: [:show]
    resources :testimonials, only: [:index]
    resources :automation, only: %i[index edit], param: :uuid do
      collection do
        get :with_feedback
        get :admin
        get :tooltip_locked
      end
    end
  end

  namespace :maintaining do
    root to: "dashboard#show"
    resources :submissions, only: [:index]
    resources :exercise_representations
    resources :site_updates, except: [:destroy]
  end

  namespace :contributing do
    root to: "dashboard#show"
    resources :contributors, only: [:index]
    resources :tasks, only: [:index], param: :uuid do
      get :tooltip, on: :member
    end
  end
  namespace :training_data do
    root to: "dashboard#index"

    get "external" => "external#index"
    patch "become_trainer" => "external#become_trainer"

    resources :code_tags_samples, only: %i[index show] do
      get :next, on: :collection
    end
  end

  resource :community, only: %i[show], controller: "community"

  namespace :community do
    resources :stories, only: %i[index show]
    resources :videos, only: %i[index show]
    resources :brief_introductions, only: %i[index]
    resources :interviews, only: %i[index]
  end

  resources :tracks, only: %i[index show] do
    get :about, on: :member

    resource :build, only: %i[show], controller: "tracks/build" do
      get :syllabus_tooltip
      get :representer_tooltip
      get :analyzer_tooltip
      get :test_runner_tooltip
      get :practice_exercises_tooltip
    end

    resources :concepts, only: %i[index show], controller: "tracks/concepts" do
      get :tooltip, on: :member
    end

    resources :exercises, only: %i[index show edit], controller: "tracks/exercises" do
      member do
        get :tooltip
        get :no_test_runner
      end

      resources :iterations, only: [:index], controller: "tracks/iterations"

      resource :mentor_request, only: %i[new show], controller: "tracks/mentor_requests" do
        get :no_slots_remaining
        get :get_more_slots
      end
      resources :mentor_discussions, only: %i[index show], controller: "tracks/mentor_discussions" do
        collection do
          get :tooltip_locked
        end
      end
      resources :solutions, only: %i[index show], controller: "tracks/community_solutions" do
        collection do
          get :tooltip_locked
        end
      end

      resources :articles, only: %i[index show], controller: "tracks/articles"
      resources :approaches, only: %i[index show], controller: "tracks/approaches"

      resource :dig_deeper, only: %i[show], controller: "tracks/dig_deeper" do
        get :tooltip_locked
      end
    end

    member do
      post :join
    end
  end
  resources :exercises, only: %i[show], controller: "generic_exercises", as: :generic_exercises do
    member do
      get :approaches
    end
  end

  resource :user_onboarding, only: %i[show create], controller: "user_onboarding"
  resource :journey, only: [:show], controller: "journey" do
    member do
      get :solutions
      get :reputation
      get :badges
    end
  end

  resources :challenges, only: [:show] do
    post :start, on: :member
    get :implementation_status, on: :member
    get "implementation_status/:track_slug" => "challenges#track_implementation_status", on: :member, as: :track_implementation_status
  end

  # ############ #
  # Unsubscribe  #
  # ############ #
  resource :unsubscribe, only: %i[show update], controller: "unsubscribe" do
    patch :all
  end

  # #### #
  # Blog #
  # #### #
  resources :blog_posts, only: %i[index show], path: "blog"

  get "donate" => "donations#index", as: :donate
  get "donated" => "donations#donated", as: :donated

  # #### #
  # SEO #
  # #### #
  get "robots" => "sitemaps#robots_txt", as: :robots_txt
  get "sitemap" => "sitemaps#index", as: :sitemap
  get "sitemap-general" => "sitemaps#general", as: :sitemap_general
  get "sitemap-profiles" => "sitemaps#profiles", as: :sitemap_profiles
  get "sitemap-tracks-:track_id" => "sitemaps#track", as: :sitemap_track

  root to: "pages#index"

  ##############
  # ELB routes #
  ##############
  get "health-check", to: 'pages#health_check'

  ##########
  # Errors #
  ##########
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
  get "/503", to: "errors#internal_error"

  ###################
  # Adverts & Perks #
  ###################
  resources :adverts, controller: "partner/adverts", only: [] do
    get :redirect, on: :member
  end
  resources :perks, only: %i[index show] do
    get :claim, on: :member
  end

  ###############
  # About Pages #
  ###############
  resource :about, controller: 'about', only: [:show] do
    resources :partners, only: %i[index show], path: "supporters/organisations", controller: "about/partners"

    get :impact
    get :testimonials
    get :team
    get :hiring
    get :hiring_content, path: "hiring/content-2", as: :hiring_2
    get :hiring_community, path: "hiring/community-3", as: :hiring_3
    get :hiring_front_end_developer, path: "hiring/front-end-developer-4", as: :hiring_4
    get :hiring_rails_developer, path: "hiring/rails-developer-5", as: :hiring_5
    get :individual_supporters, path: "supporters/individuals", as: :individual_supporters
    # get :organisation_supporters, path: "supporters/organisations", as: :organisation_supporters

    # %w[packt gobridge].each do |supporter|
    #   get "supporter_#{supporter}".to_sym, path: "supporters/organisations/#{supporter}", as: "supporter_#{supporter}"
    # end
  end

  #########
  # Cohorts #
  #########
  resources :cohorts, only: [:show] do
    post :join, on: :member
  end

  #########
  # Pages #
  #########
  get "cli-walkthrough" => "pages#cli_walkthrough", as: :cli_walkthrough

  ############
  # Partners #
  ############
  get "partners/gobridge" => "partners#gobridge", as: :gobridge_partner_page
  get "partners/code-capsules/advert_redirect" => "partners#code_capsules_advert_redirect"
  get "partners/go-developer-network", to: redirect("partners/gobridge")
  get "partners/gdn", to: redirect("partners/gobridge")

  ##################
  # Special routes #
  ##################
  get "site.webmanifest" => "meta#site_webmanifest"
  get ".well-known/apple-developer-merchantid-domain-association" => "meta#apple_developer_merchantid_domain_association"
  get "avatars/:id/:version" => "avatars#show"

  #################
  # Legacy routes #
  #################
  get "solutions/:uuid" => "legacy#solution"
  get "my/solutions/:uuid" => "legacy#my_solution"
  get "mentor/solutions/:uuid" => "legacy#mentor_solution"

  %i[installation learning resources tests].each do |doc|
    get "tracks/:slug/#{doc}", to: redirect("docs/tracks/%{slug}/#{doc}")
  end

  get "values", to: redirect("about")
  get "team", to: redirect("about/team")
  get "team/staff", to: redirect("team")
  get "team/staff", to: redirect("contributors")

  get "team/contributors", to: redirect("contributing/contributors")
  get "team/mentors", to: redirect("contributing/contributors?category=mentoring")
  get "team/maintainers", to: redirect("contributing/contributors?category=maintaining")

  get "terms-of-service", to: redirect("docs/using/legal/terms-of-service")
  get "privacy-policy", to: redirect("docs/using/legal/privacy-policy")
  get "cookie-policy", to: redirect("docs/using/legal/cookie-policy")
  get "code-of-conduct", to: redirect("docs/using/legal/code-of-conduct"), as: :code_of_conduct
  get "accessibility", to: redirect("docs/using/legal/accessibility")
  get "contact", to: redirect("docs/using/contact")
  get "cli", to: redirect("docs/using/solving-exercises/working-locally")
  get "report-abuse", to: redirect("docs/using/report-abuse")
  get "become-a-mentor", to: redirect("mentoring")
  get "my/settings", to: redirect("settings")

app/controllers/about/partners_controller.rb
class About::PartnersController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @num_individual_supporters = User::Data.donors.count
    @partners = Partner.where.not(support_markdown: '')
  end

  def show
    @org = Partner.select(:name, :slug, :description_markdown).find_by!(slug: params[:id])
  end
end

app/views/about/hiring.html.haml
- content_for :meta_title, "Exercism's Hiring!".html_safe
- content_for :meta_description, "Come and join a passionate team making programming education fun and effective. Here are some of the roles we’re hiring for.".html_safe
- content_for :canonical_url, hiring_about_url
- require_stylesheet "about"

= render ViewComponents::AboutNav.new(:hiring)

#page-hiring
  %header
    .lg-container.c-shapes
      = graphical_icon "exercism-face"
      %h1.text-h1.mb-12 We're not currently hiring.
      %p.text-p-2xlarge Please check back in the future for new roles!

app/views/about/impact.html.haml
- content_for :meta_title, "Exercism's Impact Report".html_safe
- content_for :meta_description, "We've provided over 310 million minutes of free learning to over a million people. Learn more in our impact report!".html_safe
- content_for :canonical_url, impact_about_url
- require_stylesheet "about"

= render ViewComponents::AboutNav.new(:impact)

#impact-page
  %header.pt-48.flex.flex-col.items-center{ class: 'mb-[-130px] md:h-[500px] h-[600px]' }
    .md-container.c-shapes-impact.c-shapes-1
    %h1.text-h5.text-textColor6.mb-16.flex.items-center
      = graphical_icon "report", css_class: 'h-[26px] w-[26px] filter-textColor6 mr-16'
      Exercism Impact Report
    %h2.text-h0.mb-12.text-center{ class: 'max-w-[800px]' }
      We&apos;ve provided
      %strong{ class: 'pl-8 pr-12 font-bold bg-[url(graphics/impact-highlight.svg)] bg-[length:100%_100%] text-textColor1NoDark' } 310,569,762
      %strong{ class: 'pl-8 pr-8 mr-[-8px] font-bold bg-[url(graphics/impact-highlight.svg)] bg-[length:100%_100%] text-textColor1NoDark' } minutes
      of free education.
    %p.font-medium.text-textColor6.text-24.leading-160.text-center{ class: 'max-w-[780px]' }
      And we provide another ~285,340 minutes every day!
      %br
      All on a free, open source project funded by people like you.

  .md-container.mb-48
    .flex.flex-col.md:flex-row.md:items-stretch
      .md:mr-32.mb-40.md:mb-0{ class: 'w-fill md:max-w-[380px]' }
        .shadow-lgZ1.py-8.rounded-16.mb-32.bg-backgroundColorA.overflow-hidden
          .py-12.px-32.bg-backgroundColorF
            %h3.label-large Students
            .text-purple.font-semibold.text-40.leading-150{ class: 'h-[60px]' }
              = render ReactComponents::Impact::Stat.new(:sign_up_metric, Metrics.num_users.to_i)

          .py-12.px-32.bg-backgroundColorB
            %h3.label-large Exercise Submissions
            .text-purple.font-semibold.text-40.leading-150{ class: 'h-[60px]' }
              = render ReactComponents::Impact::Stat.new(:submit_submission_metric, Metrics.num_submissions.to_i)

          .py-12.px-32
            %h3.label-large Mentoring Discussions
            .text-purple.font-semibold.text-40.leading-150
              = render ReactComponents::Impact::Stat.new(:mentoring_discussions_metric, Metrics.num_discussions.to_i)

        .bg-backgroundColorB.shadow-base.py-16.px-24
          %p.text-p-large.mb-8
            %span.text-h5 Exercism teaches #{Track.active.count} programming languages
            from #{Track.active.order('title ASC').first.title} to #{Track.active.order('title ASC').last.title},
            using a unique blend of learning, practicing, and mentoring.
          %p.text-h5 Everything on Exercism is 100% free.

      .shadow-lg.flex-grow.bg-backgroundColorB.rounded-16.py-48.px-24.relative
        .absolute.w-full.shadow-sm.text-h5.py-6.px-16.rounded-24.bg-backgroundColorA.flex.flex-row.items-center.whitespace-nowrap{ class: 'top-0 left-1/2 -translate-y-1/2 -translate-x-1/2' }
          = graphical_icon "graph-stats-gradient", css_class: 'h-[24px] w-[24px] mr-12'
          Live activity on Exercism
        = ReactComponents::Impact::Map.new

  .md-container.mb-64
    .grid.grid-cols-1.gap-20.md:grid-cols-2.lg:grid-cols-3
      .flex.flex-col.py-20.px-24
        .flex.items-center.mb-12
          = image_tag "photos/twitter-dapritchard_.jpg", class: 'w-[40px] h-[40px] rounded-circle mr-12'
          .flex.flex-col
            .label-large David Pritchard
            .text-p-base.text-textColor6 @dapritchard_
          = link_to icon('external-site-twitter', 'Twitter', css_class: 'filter-twitter h-[16px] w-[16px]'), "https://twitter.com/dapritchard_/status/1549978935995338753", class: 'ml-auto p-8'
        %p.text-p-large
          %em.not-italic.font-medium.text-purple @exercism_io
          is really incredible. My submission was failing it's tests…I asked for mentoring to help straighten things out, and within 15 minutes someone had messaged me explaining my error.

      .flex.flex-col.py-20.px-24
        .flex.items-center.mb-12
          = image_tag "photos/twitter-zippkode.jpg", class: 'w-[40px] h-[40px] rounded-circle mr-12'
          .flex.flex-col
            .label-large Karl 🇺🇦
            .text-p-base.text-textColor6 @zippcode
          = link_to icon('external-site-twitter', 'Twitter', css_class: 'filter-twitter h-[16px] w-[16px]'), "https://twitter.com/zippkode/status/1561075536834838530", class: 'ml-auto p-8'
        %p.text-p-large
          \…I worked on the Ruby strings exercises at
          %em.not-italic.font-medium.text-purple @exercism_io
          This platform forces me to slow down and actually logically solve the tasks…


      .flex.flex-col.py-20.px-24
        .flex.items-center.mb-12
          = image_tag "photos/twitter-alebaffa.jpg", class: 'w-[40px] h-[40px] rounded-circle mr-12'
          .flex.flex-col
            .label-large Alessandro Baffa
            .text-p-base.text-textColor6 @alebaffa
          = link_to icon('external-site-twitter', 'Twitter', css_class: 'filter-twitter h-[16px] w-[16px]'), "https://twitter.com/alebaffa/status/1545972418497302528", class: 'ml-auto p-8'
        %p.text-p-large
          I've always loved
          %em.not-italic.font-medium.text-purple @exercism_io
          because you learn not only the syntax of a language, but also its dev environment: how to setup tests, packaging and build. Fantastic resource!

  .md-container.mb-64
    .flex.flex-col.md:flex-row
      .md:mr-32.mb-48.md:mb-0.shadow-lg.flex-grow.bg-backgroundColorA.rounded-16.py-40.px-48
        %h2.text-h1.mb-32 Exercism is powered by huge team of wonderful volunteers.
        .grid.grid-cols-1.gap-20.lg:grid-cols-3
          .flex.flex-col
            .text-40.leading-150.font-semibold.text-purple 19,603
            .label-large Mentors
          .flex.flex-col
            .text-40.leading-150.font-semibold.text-purple 5,508
            .label-large Code Contributors
          .flex.flex-col
            .text-40.leading-150.font-semibold.text-purple 3
            .label-large Full-time Staff

        .flex.flex-wrap.mt-32.overflow-y-hidden{ class: 'h-[76px]' }
          - @contributor_avatars.each do |avatar|
            = image_tag avatar, class: 'bg-backgroundColorA h-[32px] w-[32px] mr-[-14px] mb-12 rounded-circle'

      %div{ class: 'w-fill md:max-w-[374px]' }
        .py-24.px-24.pt-60.shadow-base.mb-32.bg-backgroundColorA.relative
          .absolute.bg-lightGold.rounded-circle.w-48.text-24.p-12{ class: 'top-0 -translate-y-1/2' } 🙌
          %h3.text-h4.mb-8 Has Exercism helped you become a better developer?
          %p.text-p-large.mb-16 If Exercism has helped your career prospects or given you joy, please consider financially supporting us.
          %p.text-p-large Only 1% of people that use Exercism support us. Please be one of them.

        = link_to donate_path, class: "btn btn-base btn-secondary" do
          %span See how you can support us
          = graphical_icon "arrow-right"

  .md-container.mb-64
    %h3.text-h3.text-center.mb-16 A special thanks to these organisations…
    .logos.flex.items-center.justify-center.flex-wrap.gap-64.mb-24
      = icon "mozilla", "Mozilla", category: :partners, css_class: "mozilla h-48 filter-textColor1"
      = icon "gobridge", "GoBridge", category: :partners, css_class: "gobridge h-[80px]"
      = icon "chicago", "University of Chicago", category: :partners, css_class: "chicago h-48"
      = icon "packt", "Packt Publishing", category: :partners, css_class: 'h-48'
    .text-center.text-18.leading-150.text-textColor6.font-semibold
      And over
      = link_to "700 individuals donors!", individual_supporters_about_path, class: 'underline hover:text-lightBlue'

  .impact-chart-container.bg-repeat.overflow-hidden{ class: 'bg-[#221E31] bg-[length:90px] bg-[url(photos/chart-bg.jpg)]' }
    .md-container
      .pt-48.flex.flex-col.items-center
        .flex.flex-col.text-center{ class: "max-w-[927px]" }
          = graphical_icon "graph-stats-ascend", css_class: "mb-16 mx-auto h-[67px] w-[64px]"
          %h2.text-h1.leading-128.text-white.mb-16
            We&apos;ve grown to over 1M students entirely by word of mouth.
          %p.text-gray.text-p-2xlarge
            We work closely with our community to understand how to evolve Exercism
            to be the best it can be, and they reward us by sharing with their
            friends.

    %div{ class: 'h-[480px]' }
      = render ReactComponents::Impact::Chart.new

  -# .relative{ class: 'h-[900px]' }
    = ReactComponents::Impact::Chart.new
    .absolute{ class: 'top-[50px] left-0 right-0' }
      .flex.flex-col.items-center
        .flex.flex-col.text-center{ class: "max-w-[927px]" }
          = graphical_icon "graph-stats-ascend", css_class: "mb-16 mx-auto h-[67px] w-[64px]"
          %h2.text-h1.leading-128.text-white.mb-16
            We&apos;ve grown to over 1M students entirely by word of mouth.
          %p.text-gray.text-p-2xlarge
            We work closely with our community to understand how to evolve Exercism
            to be the best it can be, and they reward us by sharing with their
            friends.

  .sm-container.mb-64.relative{ class: 'mt-[-64px]' }
    .bg-backgroundColorA.flex.flex-col.text-center.justify-center.rounded-32.pt-24.md:pb-40.pb-24.md:px-48.px-24.shadow-lgv2
      .text-48.leading-130.mb-8 🚀
      %h2.text-h1.mb-12 Become rocket fuel for our mission
      %p.text-p-2xlarge.mb-36.text-center.text-textColor6.font-medium
        We&apos;ve built everything for under $500,000. Imagine what we could do with
        more significant funding! Could you be the one to make it happen?
      .flex.flex-col.border.border-2.border-gradient.rounded-16.md:px-40.px-24.py-24.shadow-smZ1
        .flex.flex-col.gap-8.md:gap-0.items-center.mx-auto.mb-24.md:flex-row
          = image_tag "team/jeremy-walker.jpg", alt: "A photo of Jeremy Walker", class: 'w-[64px] h-[64px] md:mr-24 md:mb-4 rounded-circle'
          .flex.flex-col.text-left
            .md:text-h4.text-h5.mb-4
              Interested in supporting Exercism as an organisation?
            .leading-regular.text-textColor5.text-18
              Get in touch with
              = succeed(',') do
                %span.text-textColor2.font-medium Jeremy Walker
              Co-founder & CEO
        = link_to "mailto:jeremy@exercism.org", class: "btn btn-primary" do
          = graphical_icon "envelope", css_class: "mr-16"
          %span.md:text-16.text-14 jeremy@exercism.org

  .lg-container.mb-64
    .c-shapes-impact.c-shapes-1
      %h2.text-h1.text-center{ class: "max-w-[800px] mx-auto" }
        Over 85,000 students have left testimonials to thank their mentors.

    .md-container{ class: "bg-[var(--backgroundColorImpactPage)]" }
      %article.testimonials.pt-40
        = ReactComponents::Impact::TestimonialsList.new(params)

app/views/about/show.html.haml
- content_for :meta_title, "About Exercism"
- content_for :meta_description, "Learn about Exercism: our vision, mission, and strategy."
- content_for :canonical_url, about_url
- require_stylesheet "about"

= render ViewComponents::AboutNav.new

#page-about
  %header.pb-56.c-header-with-bg
    .md-container.flex.flex-col.items-center.c-shapes.c-shapes-1
      = graphical_icon "exercism-face", css_class: "logo mb-8"
      %h1.text-h0.mb-16 Exercism
      %hr.c-divider.mb-16
      %p.text-p-3xlarge.text-textColor2.mb-40.text-center
        We’re building a place where anyone can learn and master programming for free, without ever feeling lost or stupid.
      .grid.grid-1.md:grid-cols-2-auto.gap-24
        = link_to donate_path, class: 'btn-l btn-primary' do
          Donate to Exercism
          = graphical_icon "arrow-right"
        -# TODO
          = link_to "Support Exercism (for organisations)", supporters_page_path, class: 'btn-l btn-enhanced'

  .md-container
    .purpose.border-t-4.md:border-t-0.md:border-l-6.py-28.my-40.md:my-56.md:py-40.px-32.md:px-64.flex.items-start.lg:items-center.flex-col.lg:flex-row.mb-64
      .info
        %h2.text-h1.mb-16.flex.items-center
          = graphical_icon "purpose"
          Purpose
        %p.text-p-2xlarge
          We're here to help everyone get really good at programming, regardless of their background.
          We want to share our love of programming, and help people upskill as part of their upward social mobility.
      = graphical_icon "purpose", category: 'graphics', css_class: 'graphic mt-16 lg:mt-0 lg:ml-40 xl:ml-80'

    .goals.mb-80.grid.grid-cols-1.md:grid-cols-3.gap-x-40.gap-y-24
      .goal
        .number 1
        %h3 Attain mastery
        %p We want people to experience the joy of programming — the deep satisfaction from being a fluent programmer.

      .goal
        .number 2
        %h3 Have Fun
        %p Developing programming skills should be empowering and fun, not competitive, frustrating or stressful.

      .goal
        .number 3
        %h3 Social Mobility
        %p We want everyone, especially the economically deprived, to achieve upward mobility through learning to code.

    .principles.flex.flex-col.items-center
      = graphical_icon "principles", css_class: 'graphic'
      %h2.text-h1.mb-24 Principles
      %hr.c-divider.mb-36

      %ul
        %li.text-p-2xlarge Exercism should be enjoyable, challenging and valuable.
        %li.text-p-2xlarge Exercism should encourage a growth-mindset, clear and empathetic communication, and emphasize the value in learning together.
        %li.text-p-2xlarge Exercism should feel safe and nurturing.
        %li.text-p-2xlarge Exercism focusses on the learning journey, not the destination. The process and enjoyment of learning is more important than absolute factual correctness.

    .leadership.flex.items-start.pt-64.pb-80.flex-col-reverse.lg:flex-row
      = graphical_icon "team", category: 'graphics', css_class: 'graphic self-center md:self-start mt-20 lg:mt-0 m-auto'

      .info
        = graphical_icon "contributing-header", css_class: 'icon'
        %h2.text-h1.mb-16 How Exercism is run
        %p.text-p-2xlarge.mb-40 Exercism is developed through a mixture of top-down leadership and a collaborative community. We believe that most decisions are worth their taking time over, and so we think hard before we act.

        %h3.text-h3.mb-16 Reflective
        %p.text-p-xlarge.mb-40 We focus on being strategy-driven and product-driven, looking to the long term, not just the immediate impact, and considering the holistic impact of decisions. We work closely with key volunteer contributors to canvas opinions and knowledge, understanding our strengths and weaknesses and trying to improve Exercism daily, while also staying focussed on our long-term vision.

        %h3.text-h3.mb-16 A small team with a big vision
        %p.text-p-xlarge.mb-40 We also place a high focus on quality. We want what we do to be good - to work well, be accessible to all, and to be innovative. We have a tiny core team who take responsibility for ensuring that Exercism grows and evolves in line with its vision. Through donations from our community, philanthropists and philanthropic foundations, we are expanding our team in a sustainable and responsible way. We have funding milestones that we publicize and fundraise towards, which allow us to hire more people to develop further.

        %h3.text-h3.mb-16 Grounded in ethics
        %p.text-p-xlarge We try to pay fairly, respecting and considering both the time and value of our staff and the generosity of our donors. We act ethically as a company and as an employer, treating our team with respect and never asking something of them that we wouldn’t do ourselves, and not using techniques or technologies that we wouldn't want used on us.

    .donate-section.px-24.lg:px-64.py-24.lg:py-40.flex.items-start.flex-col.lg:flex-row
      = graphical_icon "building-with-gradient", css_class: 'icon mb-16 lg:mb-0'
      .info.flex.flex-col.md:items-start
        %h2.text-h1.mb-12 Help us bring the joy of programming to everyone, everywhere ✨
        %p.text-p-2xlarge.mb-28 We rely on open-source contributions and cash donations to achieve our mission. Can you spare some time or money to support our mission?
        .grid.grid-cols-1.md:grid-cols-2-auto.gap-24
          = link_to donate_path, class: 'btn-l btn-primary' do
            %span Donate to Exercism

          = link_to contributing_tasks_path, class: 'btn-l btn-enhanced' do
            %span See tasks that need help
            = graphical_icon "arrow-right"

      = graphical_icon "floating-cash", category: 'graphics', css_class: 'graphic md:hidden lg:block lg:ml-48 lx:ml-96 mt-28 lg:mt-0 self-center lg:self-start'

app/views/about/testimonials.html.haml
- content_for :meta_title, "Exercism's Testimonials".html_safe
- content_for :meta_description, "Over 85,000 testimonials from students to our mentors".html_safe
- content_for :canonical_url, testimonials_about_url
- require_stylesheet "about"

= render ViewComponents::AboutNav.new(:impact)

#impact-page.pt-32
  .lg-container.mb-64
    .c-shapes-impact.c-shapes-1
      %h2.text-h1.text-center{ class: "max-w-[800px] mx-auto" }
        Over 85,000 students have left testimonials about their mentors.

    .md-container
      %article.testimonials.pt-40
        = ReactComponents::Impact::TestimonialsList.new(params)